### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by zxcqlf** [JiawangBian/SC-SfMLearner-Release#10]
Hi, when I evaluate the result using the method given by "Evaluation", I can't get the results like t_err, r_err. How can I get this two errors?

Thank you so much.

**Comment by JiawangBian** [comment]
You may use the evaluation code (C++) by KITTI odometry dataset. Note that you should alighn the global scale and then evaluate it.

**Comment by zxcqlf** [comment]
Thanks again!
