### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by SeokjuLee** [JiawangBian/SC-SfMLearner-Release#11]
Is it fine to train all losses together without pre-trained model? 
In my case of scratch training (simply tried ./train_resnet_256.sh), the photometric loss doesn't fall under around 1.0.

**Comment by JiawangBian** [comment]
it doesn't matter. photometric loss could not be 0. can you see validation error (absrel) decreasing?

**Comment by SeokjuLee** [comment]
The validation error (absrel) keeps the same (0.4515).

**Comment by JiawangBian** [comment]
it is a bug as in issue#2.

**Comment by SeokjuLee** [comment]
Oh I got it Thanks!
