### ISSUE TITLE
visualization of valid mask gained by src_pixel_coords

### ISSUE THREAD

**Issue by liujiaheng** [JiawangBian/SC-SfMLearner-Release#15]
Hi, Have you ever visualized the valid mask gained by src_pixel_coords?
![image](https://user-images.githubusercontent.com/27964642/65333683-87007200-dbf3-11e9-97bf-7bf98382e6f8.png)

![image](https://user-images.githubusercontent.com/27964642/65333150-86b3a700-dbf2-11e9-9c6b-fab8735f40b1.png)
![image](https://user-images.githubusercontent.com/27964642/65333181-93d09600-dbf2-11e9-80f9-3847035cd1e8.png)
I find that the forward valid mask got by target image depth always is 0, which is wrong, the backward valid mask got by source image depth is right.
Looking forward to your reply!

**Comment by JiawangBian** [comment]
didn't visualize that in training, but showed the weight mask in figure 2, which was cropped by valid mask. The code just computed co-viewed regions between two image. It should not be wrong when reverse two inputs.
