### ISSUE TITLE
Geometry consistency loss vs forward back depth consistency loss in DF-Net

### ISSUE THREAD

**Issue by SaiK95** [JiawangBian/SC-SfMLearner-Release#17]
Hi, 

I was going through your paper and the algorithm looks great! I have a question about the geometry consistency loss, however. 

Can you elaborate on the difference between this loss and the depth consistency loss in [DF-Net](https://arxiv.org/pdf/1809.01649.pdf). I'm talking about eq(7) in Section 3.4 (page 8). 

Thanks!

**Comment by JiawangBian** [comment]
Have a quick scan of DF-Net. it looks similar but we can differentiate that in following aspects:
1. Regarding high-level idea, we propose geometry consistency loss for constraining the scale, while they did not realize this problem. 
2. In implementation, we use bilinear interpolation and relative error, while they use absolute error and their warping is unclear to me (i may need check their codes for details).
3. we use GC for masking dynamics, while their valid mask is from optical flow.

**Comment by SaiK95** [comment]
Thanks for clarifying! 

As for the second point, I believe they use bilinear interpolation as well. But I understand the differences :)
