### ISSUE TITLE
README link

### ISSUE THREAD

**Issue by TopGun666** [JiawangBian/SC-SfMLearner-Release#22]
Hi Jiawang,

As we can see, there is a statement in your `README.md`.
> and visualize the training progress by opening https://localhost:6006 on your browser.
However, it cannot be loaded. What's wrong with it？Maybe it is just a local link?

Best regards,
Yu

**Comment by Huangying-Zhan** [comment]
Hi Yu, 
you need to run `tensorboard --logdir=checkpoints/` before opening the localhost.

**Comment by TopGun666** [comment]
@Huangying-Zhan Thanks  a lot for your reply.
