### ISSUE TITLE
Finetuning Error

### ISSUE THREAD

**Issue by TopGun666** [JiawangBian/SC-SfMLearner-Release#25]
Hi  Jiawang @JiawangBian ,

How could you use the pre-trained model to do model finetuning? When I add the path of the pre-trained model to `finetune_csk+k_resnet_256.sh`, it outputs some errors below. Compared with 
[Clement Pinard's SfMLearner implementation](https://github.com/ClementPinard/SfmLearner-Pytorch), your `train.py` has changed something (just like `output_writers`)about the part. What do you think about it?
> => creating model
=> using pre-trained weights for PoseNet
=> using pre-trained weights for DispNet
=> setting adam solver
N/A% (0 of 200) |                                                                          | Elapsed Time: 0:00:00 ETA:  --:--:--
Traceback (most recent call last):
  File "train.py", line 423, in <module>
    main()
  File "train.py", line 190, in main
100% (472 of 472) |########################################################################| Elapsed Time: 0:00:00 ETA:  00:00:00
NameError: name 'output_writers' is not defined

Regards,
Yu

**Comment by JiawangBian** [comment]
Hi,

It may be some grammar errors in previous version. Could you try the latest code by "git pull"?

Best,
Jiawang

**Comment by TopGun666** [comment]
I'll try it. Thank you.
