### ISSUE TITLE
Visual pose evaluation

### ISSUE THREAD

**Issue by Samyer** [JiawangBian/SC-SfMLearner-Release#28]
Hi, I used test_vo.py to visualize the pose results of SfMLearner. There are some problems. Can you share the code to visualize the pose results of SfMLearner?

**Comment by JiawangBian** [comment]
https://github.com/Huangying-Zhan/Depth-VO-Feat/tree/master/tools

**Comment by Samyer** [comment]
> https://github.com/Huangying-Zhan/Depth-VO-Feat/tree/master/tools

Thank you for your reply. How to save predictions.npy in txt format and then use this tool.
