### ISSUE TITLE
Undefined names

### ISSUE THREAD

**Issue by cclauss** [JiawangBian/SC-SfMLearner-Release#3]
[flake8](http://flake8.pycqa.org) testing of https://github.com/JiawangBian/SC-SfMLearner-Release on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./train.py:190:91: F821 undefined name 'output_writers'
            errors, error_names = validate_with_gt(args, val_loader, disp_net, 0, logger, output_writers)
                                                                                          ^
./train.py:192:104: F821 undefined name 'output_writers'
            errors, error_names = validate_without_gt(args, val_loader, disp_net, pose_net, 0, logger, output_writers)
                                                                                                       ^
./kitti_eval/depth_evaluation_utils.py:121:9: F821 undefined name 'LinearNDInterpolator'
    f = LinearNDInterpolator(ij, d, fill_value=0)
        ^
3     F821 undefined name 'LinearNDInterpolator'
3
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by JiawangBian** [comment]
Sorry, forget to say that I use python 3.6 for training and testing, while using python 2.7 for depth evaluation. It is because the evaluation code is copied directly from tinghui zhou's tensorflow frameowrk.

**Comment by JiawangBian** [comment]
I think that there are just some small syntax changes should be made to be compatible with python 3.6 or 3.7. I would be great If you are willing to help with this.
