### ISSUE TITLE
Question about depth evaluation

### ISSUE THREAD

**Issue by CongFang** [JiawangBian/SC-SfMLearner-Release#30]
Hi, I evaluated the depth using the method by running

  sh scripts/run_depth_test.sh

But, I only got the depth predictions. So, I used the code based on Clement Pinard's SfMLearner implementation

  test_disp.py

But, the **depth results** is not as good as the reported ones

  | Dataset | AbsRel | SqRel | RMS | RMSlog | <1.25 | <1.252 | <1.253
  SC-Net repo | K | 0.137 | 1.089 | 5.439 | 0.217 | 0.830 | 0.942 | 0.975
  SC-Net run | K | 0.140 | 1.100 | 5.481 | 0.222 | 0.824 | 0.940 | 0.974

The second row is our evaluation results. **So, can you share the code for depth evaluation metrics such as AbsRel, SqRel, RMS, RMSlog and accuracy?**

Thank you so much.

**Comment by JiawangBian** [comment]
![FA51784A-C466-441B-A108-FC8BA48A45A6](https://user-images.githubusercontent.com/11647217/70201147-a1afa500-1765-11ea-9e81-b909dd27bda4.jpeg)

**Comment by CongFang** [comment]
Thinks. I will try it.

**Comment by CongFang** [comment]
Thinks. I will try it.
