### ISSUE TITLE
Run prepare data FileNotFoundError 0000000028.bin

### ISSUE THREAD

**Issue by luyao777** [JiawangBian/SC-SfMLearner-Release#35]
When I run the script `bash scripts/run_prepare_data.sh`
I got 
> FileNotFoundError: [Errno 2] No such file or directory: Path('/Dataset/kitti_raw/2011_10_03/2011_10_03_drive_0058_sync/velodyne_points/data/0000000028.bin')

And there is no `0000000028.bin` in that folder.
Have you ever met this problem?

**Comment by JiawangBian** [comment]
Yes，kitti dataset is incomplete. So I just simply remove this drive。

**Comment by luyao777** [comment]
Thanks for your reply. So what could I do to fix this problem? Is there any suggestion?

**Comment by JiawangBian** [comment]
just delete the following folder from dataset （“/Dataset/kitti_raw/2011_10_03/2011_10_03_drive_0058_sync/”）and run script again.

**Comment by luyao777** [comment]
Thanks!
