### ISSUE TITLE
the metric about poses of kitti 

### ISSUE THREAD

**Issue by hello7623** [JiawangBian/SC-SfMLearner-Release#37]
Your report is  ：

|   Models   |                     | Seq. 09 | Seq. 10 |
|------------|---------------------|---------|---------|
|   k_pose   |t_err (%)            | 11.2    | 10.1    |
|            |r_err (degree/100m)  | 3.35    | 4.96    | 

But I  use what you've provided repo to test is 

|   Models   |                     | Seq. 09 | Seq. 10 |
|------------|---------------------|---------|---------|
|   k_pose   |t_err (%)            | 12.57   | ---    |
|            |r_err (degree/100m)  | 3.34    | ---    | 

I don't know why ？

**Comment by hello7623** [comment]
I'm using the model you pretrained on kitti 
The tools used to evalute is  https://github.com/Huangying-Zhan/kitti-odom-eval.git

**Comment by JiawangBian** [comment]
Please make sure that you use "--align scale" option. Besides, note that we discard the first 9 frames in nips paper, as ORB-SLAM cannot provide full trajectory.
