### ISSUE TITLE
Global pose data in your figure

### ISSUE THREAD

**Issue by TopGun666** [JiawangBian/SC-SfMLearner-Release#38]
Hi @JiawangBian 

Thanks for your great job. I am very honored to complete my research based on your framework. I will cite your work in my paper. Could you provide me the global pose data ( ORB-SLAM, zhou et al, zhan et al and yours ) in your figure 3? Thanks a lot.

Best regards,
Yu

**Comment by JiawangBian** [comment]
Can you leave your email so that I can send you data?

**Comment by TopGun666** [comment]
Email: heyu.nwpu@gmail.com Thanks you very much.

**Comment by luyao777** [comment]
Hi,
Can you seed me a copy of the global pose data (ORB-SLAM, zhou et al, zhan et al and yours) in your figure 3? My email is luyao777@ruc.edu.cn
Many thanks.

**Comment by hello7623** [comment]
Hi！ I'm continuing to do some research based on your work, Could you provide me the global pose data ( ORB-SLAM, zhou et al, zhan et al and yours ) in your figure 3? Thanks a lot！！！My email is 981839079@qq.com

**Comment by whyygug** [comment]
@JiawangBian  Hi, I'm  doing my work based on your framework, too.  Could you provide me the global pose data ( ORB-SLAM, zhou et al, zhan et al and yours ) in your figure 3? Thank you. My email is 248378677@qq.com.
