### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by suimo** [JiawangBian/SC-SfMLearner-Release#39]
hi,I have a problem when run the script run_prepare_data.sh, it shows as follows
![image](https://user-images.githubusercontent.com/13583453/75604086-0b92dd00-5b10-11ea-86ab-249d36bc0edd.png)
I don't know how to fix it, please give me some advice, thanks a lot!

**Comment by LZL-CS** [comment]
> hi, I have a problem when running the script run_prepare_data.sh, it shows as follows
> ![image](https://user-images.githubusercontent.com/13583453/75604086-0b92dd00-5b10-11ea-86ab-249d36bc0edd.png)
> I don't know how to fix it, please give me some advice, thanks a lot!

I have got a similar result when I runing the "script run_prepare_data.sh", can I know how do you set the data"#TRAIN_SET=/media/bjw/Disk/Dataset/kitti_256/" ?

**Comment by JiawangBian** [comment]
It seems that your original dataset (kitti raw dataset) is not completely downloaded. 
"#TRAIN_SET=/media/bjw/Disk/Dataset/kitti_256/" is the output of this script.
You may also refer to 'https://github.com/ClementPinard/SfmLearner-Pytorch' for data preprare.

**Comment by suimo** [comment]
hi, thanks a lot for your advise. I just rm ipynb_checkpoints in the folder 2011_09_26 and it's fixed
