### ISSUE TITLE
FILE ERRORS

### ISSUE THREAD

**Issue by hello7623** [JiawangBian/SC-SfMLearner-Release#41]
I have a problem related to the file, it seems that there is a lack of cloud data, but I downloaded it from the official website again and found that the official website was already missing. Do you know what happened?
![未命名图片](https://user-images.githubusercontent.com/36818370/76098295-2976ab00-6004-11ea-97af-8a84ca6ef2ee.png)

**Comment by JiawangBian** [comment]
Yes, I also met this issue, and I just removed this sequence (drive_0058) from raw dataset.

**Comment by hello7623** [comment]
OK ，thanks ！
