### ISSUE TITLE
first  ？

### ISSUE THREAD

**Issue by Dream-Runner-Yu** [JiawangBian/SC-SfMLearner-Release#45]
Are you sure  that is the first work to show that deep networks trained using unlabelled monocular videos can predict globally scale-consistent camera trajectories over a long video sequence ???

**Comment by JiawangBian** [comment]
To the best of my knowledge, it is. Some previous work may have this potential, but they did not  explictly discuss the scale consistency problem, which is the key problem of using such unsupervised methods for visual odometry purpose.
