### ISSUE TITLE
image problem

### ISSUE THREAD

**Issue by xiaoyang666** [JiawangBian/SC-SfMLearner-Release#49]
Hi,
   I used the original data set downloaded by kitti, after running run_prepare_data.sh command to get the data set kitti_256, and then after train_resnet18_depth_256.sh, the following problems occurred. Is there something wrong with me? My system is ubuntu16.04 python=3.6 pytorch=1.2 cuda=10.
Thanks a lot

**Comment by xiaoyang666** [comment]
ValueError:Image of type float must be between -1 and 1
![Screenshot from 2020-06-21 18-47-21](https://user-images.githubusercontent.com/37059168/85222887-1809b100-b3f1-11ea-93cd-212ff686e73c.png)

**Comment by JiawangBian** [comment]
It says that the the "imresize" function requires that the image of type float must be between -1 and 1. Here, the image is first loaded in "sequence_floder.py" as float type by 
"
def load_as_float(path):
    return imread(path).astype(np.float32)
"

Can you try to change it to 
"
def load_as_float(path):
    return imread(path)
"
and have a try?

**Comment by JiawangBian** [comment]
Or you can try to change the line76 in custom_transforms.py

scaled_images = [imresize(im, (scaled_h, scaled_w)) for im in images]

to 

scaled_images = [np.array(Image.fromarray(im.astype(np.uint8)).resize((scaled_w, scaled_h))).astype(np.float32) for im in images]

Also, do not forget add "from PIL import Image" before using Image.fromarray()

**Comment by xiaoyang666** [comment]
Hi,
  I'm very happy to have received your response.This change worked.
  scaled_images = [np.array(Image.fromarray(im.astype(np.uint8)).resize((scaled_w, 
  scaled_h))).astype(np.float32) for im in images]
  In the subsequent training, a problem occurred in inversed_warp.py (typeerror:grid_sample got an 
  unexpected keyword argument 'align_corners'). Normal training after deletion this.
  Thank you.

**Comment by JiawangBian** [comment]
It is due to pytorch version.
"align_corners" is a new keyword in pytorch after 1.4 (or 1.3 that I forgot).
You can update pytorch to the latest version, or you can just delete 'align_corners' in grid_sample function.
