### ISSUE TITLE
test script UnboundLocalError

### ISSUE THREAD

**Issue by xiaoyang666** [JiawangBian/SC-SfMLearner-Release#50]
Hi， 
  When I started to run the test script, the following problem occurred, this is a small problem, but I did not debug it correctly, thank you
  np.save(output_dir/'predictions.npy', predictions)
  UnboundLocalError: local variable 'predictions' referenced before assignment
![Screenshot from 2020-06-22 22-27-39](https://user-images.githubusercontent.com/37059168/85299884-7067ae00-b4d8-11ea-9576-13a1800a07ea.png)

**Comment by JiawangBian** [comment]
“0 files to test“ meas that you do not provide
a correct path of the testsets。you need download the test set （link is given in
this repo） and set the correct path in the test script。
