### ISSUE TITLE
training @ invalid syntax

### ISSUE THREAD

**Issue by huangyuan2020** [JiawangBian/SC-SfMLearner-Release#56]
when I try to run script/train_nyu.sh, there is a problem:
![image](https://user-images.githubusercontent.com/30063627/88020625-a55e3380-cb5e-11ea-8540-c39c44b8b04b.png)
Could someone tell me what is the meaning of @?

**Comment by JiawangBian** [comment]
it is Matrix multiplication operator. See

https://github.com/pytorch/pytorch/issues/1

**Comment by huangyuan2020** [comment]
thank you!
it may be my environment problem, I reinstall the requirement, now it's ok.
