### ISSUE TITLE
what does 'auto_mask' mean?

### ISSUE THREAD

**Issue by wqx854987945** [JiawangBian/SC-SfMLearner-Release#59]
Hello,

I'm browsing your paper. The algorithm looks great! I have a question about  the problem of ‘valid_mask’.

Can you explain why "auto_ mask=(diff_ img<(tgt_ img-ref_ img))*valid_ mask ; valid_ mask=auto_mask" is not mentioned in your paper? In my opinion, the modification date of these two lines of code is recent. Does that mean 'auto_mask' is not used in the paper, however it will perform better by using it?

thank you!

**Comment by JiawangBian** [comment]
yes，it is borrowed from monodepth2. it boosts performance by masking stationary points（assume that two training images are same，we should not use that）.

**Comment by wqx854987945** [comment]
Thanks for your reply！
