### ISSUE TITLE
How to implement  this in c++

### ISSUE THREAD

**Issue by Liming-Cheng** [JiawangBian/SC-SfMLearner-Release#6]
Hi, JiawangBian. 
This work is pretty good, and I want to use it in other work if it can work under model of c++.
So if I want to implement this work in c++, what should I do? 
I know I have to compile libtorch API , and convert model .th to .pt, but I don't have idea of modifying the python code to c++. Can you provide some advice?
Thank you very much!

**Comment by JiawangBian** [comment]
Sorry, i have never considered this practical problem. I guess that you can still use python code for training but just cpp for testing. As there is no complexed operation in testing, you may follow tutorials provided by pytorch library.
