### ISSUE TITLE
A question about testing VO

### ISSUE THREAD

**Issue by Nyohohoho** [JiawangBian/SC-SfMLearner-Release#61]
Thank you for everything.

I currently have some confuse about 'test_vo.py'.
The PoseNet is expected to estimate the relative pose from target view to reference view, isn't it?
If it is true, the pose should be expressed in this form: <img src="https://render.githubusercontent.com/render/math?math=P_{tgt2ref} = P_{ref}P_{tgt}^{-1}">.
Therefore, when we track the camera motion in a sequence {0, 1, 2, ..., n}, it will have to be left multiplication like: <img src="https://render.githubusercontent.com/render/math?math=(P_{n}P_{n-1}^{-1})\cdots (P_{3}P_{2}^{-1})(P_{2}P_{1}^{-1})P_{initial}">.
However, when I tried this one in testing VO, I failed.

Based on your code, I notice you use
> global_pose @  np.linalg.inv(pose_mat)

It means your formula is: <img src="https://render.githubusercontent.com/render/math?math=P_{initial}(P_{1}P_{2}^{-1})(P_{2}P_{3}^{-1})\cdots (P_{n-1}P_{n}^{-1})">.

Maybe I am lacking in study, and I am very sorry about that.
I will appreciate it very much if you could give me some hints.

**Comment by JiawangBian** [comment]
There are several corrdinates. like camera-to-world or world-to-camera. TBH, I often implement that by ploting the estimated trajectory with gt in the same figure, and tune that till they are matched.
