### ISSUE TITLE
slow training with multiple gpu

### ISSUE THREAD

**Issue by CSU-NXY** [JiawangBian/SC-SfMLearner-Release#62]
Hi, I followed #48 to use multiple gpu training. However it is kind of slower than using a single gpu.

For epoch size 1000 and GV1000:

- With batch size 4, a single gpu need about 12 minutes per epoch. 

- With batch size 12, 4 gpu need about 30 minutes per epoch.

**Comment by JiawangBian** [comment]
So I suggest using single gpu for training :)

**Comment by CSU-NXY** [comment]
XD
