### ISSUE TITLE
cant open Resnet18 model

### ISSUE THREAD

**Issue by farazBhatti** [JiawangBian/SC-SfMLearner-Release#63]
Hi, I have downloaded Resnet18 model but  the file is not opening. Maybe it is corrupted or something.
link to [file](https://onedrive.live.com/?authkey=%21AP8Z6Tl8RC8waZo&id=36712431A95E7A25%212453&cid=36712431A95E7A25) .

**Comment by JiawangBian** [comment]
it is not corrupted. You just need download it and run the code. It doesn't need decompression.
