### ISSUE TITLE
_tkinter.TclError: unknown color name "white"

### ISSUE THREAD

**Issue by liubamboo** [JiawangBian/SC-SfMLearner-Release#66]
when I run the kitti_odometry.py. A bug appear.
Traceback (most recent call last):
  File "/home/lwt/projects/SC-SfMLearner-Release/kitti_eval/eval_odom.py", line 31, in <module>
    seqs=args.seqs,
  File "/home/lwt/projects/SC-SfMLearner-Release/kitti_eval/kitti_odometry.py", line 603, in eval
    self.plot_trajectory(poses_gt, poses_result, i)
  File "/home/lwt/projects/SC-SfMLearner-Release/kitti_eval/kitti_odometry.py", line 280, in plot_trajectory
    fig = plt.figure()
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/pyplot.py", line 693, in figure
    **kwargs)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 901, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure, master=window)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 184, in __init__
    width=w, height=h, borderwidth=0, highlightthickness=0)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/tkinter/__init__.py", line 2405, in __init__
    Widget.__init__(self, master, 'canvas', cnf, kw)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/tkinter/__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown color name "white"

My environment is ubuntu 18.04, cuda 10.2 python 3.6
and pip list: 
Package            Version
------------------ -------------------
argcomplete        1.12.1
blessings          1.7
certifi            2020.6.20
colorama           0.4.4
cycler             0.10.0
decorator          4.4.2
evo                1.13.0
imageio            2.9.0
importlib-metadata 2.0.0
kiwisolver         1.3.1
matplotlib         3.3.3
mkl-fft            1.2.0
mkl-random         1.1.1
mkl-service        2.3.0
natsort            7.1.0
networkx           2.5
numpy              1.19.4
olefile            0.46
opencv-python      4.4.0.46
pandas             1.1.4
path               15.0.0
Pillow             8.0.1
pip                20.2.4
progressbar2       3.53.1
protobuf           3.14.0
Pygments           2.7.2
pyparsing          2.4.7
python-dateutil    2.8.1
python-utils       2.4.0
pytz               2020.4
PyWavelets         1.1.1
PyYAML             5.3.1
scikit-image       0.17.2
scipy              1.5.4
seaborn            0.11.0
setuptools         50.3.1.post20201107
six                1.15.0
tensorboardX       2.1
tifffile           2020.9.3
torch              1.5.1
torchvision        0.6.0a0+35d732a
tqdm               4.53.0
wheel              0.35.1
zipp               3.4.0

conda list:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
argcomplete               1.12.1                   pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
blas                      1.0                         mkl    defaults
blessings                 1.7                      pypi_0    pypi
ca-certificates           2020.10.14                    0    defaults
certifi                   2020.6.20          pyhd3eb1b0_3    defaults
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_1    defaults
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
evo                       1.13.0                   pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0    defaults
importlib-metadata        2.0.0                    pypi_0    pypi
intel-openmp              2020.2                      254    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.11                 h396b838_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
lz4-c                     1.9.2                heb0550a_3    defaults
matplotlib                3.3.3                    pypi_0    pypi
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.2.0            py36h23d657b_0    defaults
mkl_random                1.1.1            py36h0573a6f_0    defaults
natsort                   7.1.0                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1    defaults
networkx                  2.5                      pypi_0    pypi
ninja                     1.10.1           py36hfd86e86_0    defaults
numpy                     1.19.2           py36h54aff64_0    defaults
numpy-base                1.19.2           py36hfa32c7d_0    defaults
olefile                   0.46                     py36_0    defaults
opencv-python             4.4.0.46                 pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0    defaults
pandas                    1.1.4                    pypi_0    pypi
path                      15.0.0                   pypi_0    pypi
pillow                    8.0.1            py36he98fc37_0    defaults
pip                       20.2.4           py36h06a4308_0    defaults
progressbar2              3.53.1                   pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
pygments                  2.7.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.6.12               hcff3b4d_2    defaults
python-dateutil           2.8.1                    pypi_0    pypi
python-utils              2.4.0                    pypi_0    pypi
pytorch                   1.5.1           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
pytz                      2020.4                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0    defaults
scikit-image              0.17.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.11.0                   pypi_0    pypi
setuptools                50.3.1           py36h06a4308_1    defaults
six                       1.15.0           py36h06a4308_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tensorboardx              2.1                      pypi_0    pypi
tifffile                  2020.9.3                 pypi_0    pypi
tk                        8.6.10               hbc83047_0    defaults
torchvision               0.6.1                py36_cu102    pytorch
tqdm                      4.53.0                   pypi_0    pypi
wheel                     0.35.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h9ceee32_0    defaults

**Comment by JiawangBian** [comment]
check "https://github.com/Huangying-Zhan/kitti-odom-eval" which is copied to this project for evaluation.
