### ISSUE TITLE
Question about your Training time

### ISSUE THREAD

**Issue by hzfGuardian** [JiawangBian/SC-SfMLearner-Release#67]
Excuse me, I have a confusion about your training time analysis in your paper Section 4.4: 
Since you claimed that your method takes about 32 hours in training, how many epoches have you taken for such 32-hour learning? Since I tried your code and found that one epoch took roughly 1 hour.

**Comment by hzfGuardian** [comment]
@JiawangBian Hope for your response, thanks!

**Comment by JiawangBian** [comment]
Hi, I train models using a single v100. There are total 200 epochs, and one epoch contain 1000 batches with batchsize being 4. The image resolution is 256x832. If you use current version, training ResNet18 model will take 29 hours, and training ResNet50 will take 37 hours.

**Comment by hzfGuardian** [comment]
@JiawangBian Thanks! I've changed the branch to latest NeuIPS version and get the correct result.
