### ISSUE TITLE
how to align scale on sequecen 11-15 ?

### ISSUE THREAD

**Issue by fangxu622** [JiawangBian/SC-SfMLearner-Release#68]
SC-Sfmlearner output the 11-15 

http://www.cvlibs.net/datasets/kitti/eval_odometry_detail.php?&result=4e60f9922dd35ca5153fd59f2a4ff1a682d3f931 , this is your result on sequence 11-15

how to align your sequence 11-15  for comparison?

**Comment by JiawangBian** [comment]
It is not uploaded by me, but you can align the SC predicted results with other stereo-based algorithms, like ORB-SLAM2.
