### ISSUE TITLE
About the evaluation code

### ISSUE THREAD

**Issue by WBS-123** [JiawangBian/SC-SfMLearner-Release#79]
In the line 196~201 of eval_depth.py:
```python
ratio = 1
if eval_mono:
    ratio = np.median(val_gt_depth) / np.median(val_pred_depth)
    ratios.append(ratio)
    val_pred_depth *= ratio
    # val_pred_depth *= 31.289
```
What  is this code used for?
and `val_pred_depth` is modified according to  the  `val_gt_depth`, is that valid?

**Comment by JiawangBian** [comment]
it is used for recovering the metric scale because the predicted depth has an unknown scaling.
