### ISSUE TITLE
0.01 in pose decoder

### ISSUE THREAD

**Issue by leyuan-sun** [JiawangBian/SC-SfMLearner-Release#80]
https://github.com/JiawangBian/SC-SfMLearner-Release/blob/bea75b7e40b300f015a2c3607c369ca969bd6645/models/PoseResNet.py#L49

What is the meaning of this 0.01? Thanks ahead!

**Comment by JiawangBian** [comment]
it is used to stabilize the training. If the initial pose is large, the mapping between two images is weird, and it is hard to train networks with photometric loss. A small pose would make the initial two-view mapping close to the identity mapping.
