### ISSUE TITLE
Question about Depth loss

### ISSUE THREAD

**Issue by hyBlue** [JiawangBian/SC-SfMLearner-Release#9]
Hi, I've read your paper and the code and I want to ask you something about Depth loss.

When you compute photometric loss, you use depth weight mask to reduce the effects of geometric violations, right? But I want to ask the reason why this mask is unused to compute depth loss. I think it might work for both cases.

Thank you.

**Comment by JiawangBian** [comment]
If so, there may exist an extreme case: networks predict very bad resutls so that the depth maps are not consistent with each other. This leads to low-weight for most regions and reduces the weighted loss. It is not reasonable that worse predictions results in lower losses.

**Comment by hyBlue** [comment]
Then, if the network can predict pretty reasonable output, consistency mask could work for depth loss, right? such as fine-tuning only by depth  loss with mask after training without mask.
