### ISSUE TITLE
How to train monodepth2 with the rectified_nyu dataset?

### ISSUE THREAD

**Issue by jsczzzk** [JiawangBian/SC-SfMLearner-Release#91]
Hi:
Thank you for your nice work:)
I want to know how to train Monodepth2 with the rectified_nyu dataset you provided. 
The problem is that your rectified_nyu dataset provides two images for each training sample instead of the three images in Monodepth2.
Thanks in advance:)

**Comment by JiawangBian** [comment]
Just disable the "minimum loss in three images".

**Comment by jsczzzk** [comment]
Thank you for your quick reply:)
Do you mean to use only two images per sample to train Monodepth2?
If this is the case, then monodepth2 will not be able to handle occlusions. Then, did you add the Ms mask when training Monodepth2?
I have another question about which data augmentation method is used? This project or the original Monodepth2?
The differences are the color augmentation and the RandomScaleCrop augmentation.
Thanks in advance:)

**Comment by JiawangBian** [comment]
For training monodepth2, I use all the original settings. It is just another method for comparison in my paper. I do not modify it too much.

**Comment by jsczzzk** [comment]
Thank you so much:)
